### ISSUE TITLE
Do you want this? (Half finished 'reference' article)

### ISSUE THREAD

**Issue by jack-williams** [microsoft/TypeScript-New-Handbook#19]
I started writing this a while back https://github.com/jack-williams/ts-spec/blob/master/conditional-types.md

It's incomplete, out-of-date, and probably wrong in places -- but it's a starting point. I'm still planning to finish it up but there are PR's outstanding that might change a few things.

Anyway, I'm just offering it up as a resource to cannibalised.

**Comment by jack-williams** [comment]
It is probably more sensible to try and finish what I started before trying to flog it! Though, the offer remains.

**Comment by sw-yx** [comment]
this looks quite in depth! please keep going.
