### ISSUE TITLE
Making the Content Searchable

### ISSUE THREAD

**Issue by gcrev93** [microsoft/TypeScript-New-Handbook#7]
Is it possible to make the Handbook searchable?

The Outline can be a bit overwhelming and hard to find specific topics especially with longer pages like the **More on Functions** and **Classes** page.

Other suggestions on making the handbook less busy:
- Possibly remove **all** subtopics and maybe add a description.  But allow subtopics to be seen when main pages are open
- Or make the subtopics dropdowns (I'm not sure if this is the idea once the handbook is ported to the TypeScript website)

**Comment by orta** [comment]
The website will be handling search, so this can be closed 👍
